<?xml version="1.0" encoding="utf-8"?><Database Name="NDS" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=nafisa88;Initial Catalog=NDS;Integrated Security=True" SettingsObjectName="NDS.Properties.Settings" SettingsPropertyName="NDSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Login_info" Member="Login_infos">
    <Type Name="Login_info">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Patient_info" Member="Patient_infos">
    <Type Name="Patient_info">
      <Column Name="AppointmentId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaritalSatus" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AppointmentDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AppointmentTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="DoctorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Doctor_info" Member="Doctor_infos">
    <Type Name="Doctor_info">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PHONE_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LOCATION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADDRESS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SPECIALIST" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IMAGE" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="START_TIME" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="END_TIME" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
    </Type>
  </Table>
</Database>